### PR TITLE
feat: enable renovate for automatic dependency updates

### PR DESCRIPTION
**Pull request by coderbyheart**
This adds the configuration for [Renovate](https://github.com/renovatebot/renovate) which will monitor the dependencies in this project and create PRs when updates are needed.

### CODE REVIEW

**Comment by w3bdesign** [comment]
@coderbyheart 

Isn't it better to use Dependabot, as it is native to Github?

**Comment by programmiri** [comment]
Thanks Markus! I'll try it out. I had to remove dependabot from my last repo, because most updates lead to breaking changes and adjusting that manually every time was more work than updating it manually 🙈

**Comment by coderbyheart** [comment]
Dependabot is enabled by default anyway, but provides much fewer updates in my experience. Mostly security fixes. With renovate, all dependencies are updated as soon as new releases are published.

**Comment by coderbyheart** [comment]
@programmiri the important this is to have good test coverage.

**Pull request merged**
